# Generated by Django 4.2.7 on 2023-12-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
